"""
Base agent class for all specialized agents.
"""

import asyncio
import logging
from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any, Dict, List, Optional

from ..exchange.base import BaseExchange
from ..schemas import AgentStatus


class BaseAgent(ABC):
    """
    Abstract base class for all agents.

    Provides common functionality for agent lifecycle management,
    data sharing, and error handling.
    """

    def __init__(
        self,
        name: str,
        exchange: BaseExchange,
        update_interval: int = 60
    ):
        """
        Initialize base agent.

        Args:
            name: Agent name
            exchange: Exchange adapter instance
            update_interval: Update interval in seconds
        """
        self.name = name
        self.exchange = exchange
        self.update_interval = update_interval

        self.logger = logging.getLogger(f"Agent.{name}")
        self.running = False
        self.task: Optional[asyncio.Task] = None

        # Metrics
        self.signals_generated = 0
        self.errors = 0
        self.last_update: Optional[datetime] = None

        # Shared data storage
        self.latest_signals: List[Any] = []

    async def start(self):
        """Start the agent."""
        if self.running:
            self.logger.warning(f"{self.name} is already running")
            return

        self.running = True
        self.task = asyncio.create_task(self._run())
        self.logger.info(f"{self.name} started")

    async def stop(self):
        """Stop the agent."""
        if not self.running:
            return

        self.running = False
        if self.task:
            self.task.cancel()
            try:
                await self.task
            except asyncio.CancelledError:
                pass

        self.logger.info(f"{self.name} stopped")

    async def _run(self):
        """Main agent run loop."""
        while self.running:
            try:
                await self.execute()
                self.last_update = datetime.utcnow()
                await asyncio.sleep(self.update_interval)

            except asyncio.CancelledError:
                break

            except Exception as e:
                self.errors += 1
                self.logger.error(f"Error in {self.name}: {e}", exc_info=True)
                await asyncio.sleep(self.update_interval)

    @abstractmethod
    async def execute(self):
        """
        Execute the agent's main logic.

        This method should be implemented by subclasses to perform
        the agent's specific analysis and generate signals.
        """
        pass

    def get_status(self) -> AgentStatus:
        """
        Get current agent status.

        Returns:
            Agent status information
        """
        status = "running" if self.running else "stopped"
        if self.errors > 10:
            status = "error"

        return AgentStatus(
            agent_name=self.name,
            status=status,
            last_update=self.last_update or datetime.utcnow(),
            signals_generated=self.signals_generated,
            errors=self.errors
        )

    def get_latest_signals(self) -> List[Any]:
        """
        Get the latest signals generated by this agent.

        Returns:
            List of signal objects
        """
        return self.latest_signals.copy()

    def clear_signals(self):
        """Clear stored signals."""
        self.latest_signals.clear()
